backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "home"
        fields:
          - label: "Navbar Brand"
            name: "navbar_brand"
            widget: "string"
            tagname: "a.navbar-brand"
            default: "First"
          - label: "Hero Section Title"
            name: "hero_title"
            widget: "string"
            tagname: "h1.hero-title"
            default: "Hello friend!"
          - label: "Hero Section Subtitle"
            name: "hero_subtitle"
            widget: "string"
            tagname: "h2"
            default: "I’m available for freelance work."
          - label: "About Title"
            name: "about_title"
            widget: "string"
            tagname: "h2.text-white"
            default: "My Story"
          - label: "About Content"
            name: "about_content"
            widget: "markdown"
            tagname: "div.about-thumb p"
          - label: "Contact Phone"
            name: "contact_phone"
            widget: "string"
            tagname: "a.custom-btn"
            default: "120-240-9600"
          - label: "Footer Copyright"
            name: "footer"
            widget: "string"
            tagname: "footer.site-footer p"
            default: "Copyright © 2036 First Portfolio Company. All rights reserved."
